/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as ApiPublicTelemetryRouteImport } from './routes/api/public/telemetry'
import { Route as ApiPublicTelemetryStreamRouteImport } from './routes/api/public/telemetry.stream'
import { Route as ApiPublicStepAnalyzeRouteImport } from './routes/api/public/step.analyze'
import { Route as ApiPublicStepJobsIdRouteImport } from './routes/api/public/step.jobs.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiPublicTelemetryRoute = ApiPublicTelemetryRouteImport.update({
  id: '/api/public/telemetry',
  path: '/api/public/telemetry',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTelemetryStreamRoute =
  ApiPublicTelemetryStreamRouteImport.update({
    id: '/stream',
    path: '/stream',
    getParentRoute: () => ApiPublicTelemetryRoute,
  } as any)
const ApiPublicStepAnalyzeRoute = ApiPublicStepAnalyzeRouteImport.update({
  id: '/api/public/step/analyze',
  path: '/api/public/step/analyze',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicStepJobsIdRoute = ApiPublicStepJobsIdRouteImport.update({
  id: '/api/public/step/jobs/$id',
  path: '/api/public/step/jobs/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/api/public/telemetry': typeof ApiPublicTelemetryRouteWithChildren
  '/api/public/step/analyze': typeof ApiPublicStepAnalyzeRoute
  '/api/public/telemetry/stream': typeof ApiPublicTelemetryStreamRoute
  '/api/public/step/jobs/$id': typeof ApiPublicStepJobsIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/': typeof AuthenticatedIndexRoute
  '/api/public/telemetry': typeof ApiPublicTelemetryRouteWithChildren
  '/api/public/step/analyze': typeof ApiPublicStepAnalyzeRoute
  '/api/public/telemetry/stream': typeof ApiPublicTelemetryStreamRoute
  '/api/public/step/jobs/$id': typeof ApiPublicStepJobsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/api/public/telemetry': typeof ApiPublicTelemetryRouteWithChildren
  '/api/public/step/analyze': typeof ApiPublicStepAnalyzeRoute
  '/api/public/telemetry/stream': typeof ApiPublicTelemetryStreamRoute
  '/api/public/step/jobs/$id': typeof ApiPublicStepJobsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/api/public/telemetry'
    | '/api/public/step/analyze'
    | '/api/public/telemetry/stream'
    | '/api/public/step/jobs/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/'
    | '/api/public/telemetry'
    | '/api/public/step/analyze'
    | '/api/public/telemetry/stream'
    | '/api/public/step/jobs/$id'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/'
    | '/api/public/telemetry'
    | '/api/public/step/analyze'
    | '/api/public/telemetry/stream'
    | '/api/public/step/jobs/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiPublicTelemetryRoute: typeof ApiPublicTelemetryRouteWithChildren
  ApiPublicStepAnalyzeRoute: typeof ApiPublicStepAnalyzeRoute
  ApiPublicStepJobsIdRoute: typeof ApiPublicStepJobsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/telemetry': {
      id: '/api/public/telemetry'
      path: '/api/public/telemetry'
      fullPath: '/api/public/telemetry'
      preLoaderRoute: typeof ApiPublicTelemetryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telemetry/stream': {
      id: '/api/public/telemetry/stream'
      path: '/stream'
      fullPath: '/api/public/telemetry/stream'
      preLoaderRoute: typeof ApiPublicTelemetryStreamRouteImport
      parentRoute: typeof ApiPublicTelemetryRoute
    }
    '/api/public/step/analyze': {
      id: '/api/public/step/analyze'
      path: '/api/public/step/analyze'
      fullPath: '/api/public/step/analyze'
      preLoaderRoute: typeof ApiPublicStepAnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/step/jobs/$id': {
      id: '/api/public/step/jobs/$id'
      path: '/api/public/step/jobs/$id'
      fullPath: '/api/public/step/jobs/$id'
      preLoaderRoute: typeof ApiPublicStepJobsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface ApiPublicTelemetryRouteChildren {
  ApiPublicTelemetryStreamRoute: typeof ApiPublicTelemetryStreamRoute
}

const ApiPublicTelemetryRouteChildren: ApiPublicTelemetryRouteChildren = {
  ApiPublicTelemetryStreamRoute: ApiPublicTelemetryStreamRoute,
}

const ApiPublicTelemetryRouteWithChildren =
  ApiPublicTelemetryRoute._addFileChildren(ApiPublicTelemetryRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiPublicTelemetryRoute: ApiPublicTelemetryRouteWithChildren,
  ApiPublicStepAnalyzeRoute: ApiPublicStepAnalyzeRoute,
  ApiPublicStepJobsIdRoute: ApiPublicStepJobsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
